version: '3'

services:
  app:
    build:
      context: ./node
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    container_name: app
    ports:
      - 3000:3000
    depends_on:
      - db
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: "node index.js"

  db:
    image: mariadb:10.5.8
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=docker
      - MYSQL_ROOT_PASSWORD=docker
    networks: 
      - node-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    tty: true
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - app

networks:
  node-network:
    driver: bridge